version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - 127.0.0.1:8004:80
    networks:
      - net
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - net
    volumes:
      - ./jsonbox/docker/data:/data/db

  jsonbox:
    container_name: jsonbox
    build:
      context: ./jsonbox
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jsonbox-io-dev
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - net
    depends_on:
      - mongo

  redactor:
    container_name: redactor
    build: ./redactor
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - net
    volumes:
      - ./redactor/src:/home/app/redactor
      - ./redactor/models:/home/app/models
    links:
      - frontend

networks:
  net:
    driver: bridge